### ISSUE TITLE
Chat sin mensaje

### ISSUE THREAD

**Issue by ibengoa** [hubtype/botonic#485] opened 2020-01-27 11:35 UTC
Nos pasa en repetidas ocaciones, que habiendo iniciado una sesión del chat, si lo dejas un tiempo sin hacer nada, tras la recarga del chat, o el volver a abrir el navebador, se cargan los mensajes anteriores y visualmente se muestran tres puntos suspensivos como intentando conectar con Dialogflow, pero se queda ahí. No sabemos si no obtiene respuesta, si es porque la sesión finalizó.

Ayudita please!

**Comment by ibengoa** [comment] 2020-01-27 11:53
Les añado aquí el package.json por si les puede dar más información.

`
{
  "scripts": {
    "build": "webpack --env.target=all --mode=production",
    "start": "webpack-dev-server --env.target=dev"
  },
  "sideEffects": false,
  "dependencies": {
    "@botonic/plugin-dialogflow": "0.9.0-beta.1",
    "@botonic/react": "^0.10.1",
    "@rehooks/local-storage": "^1.4.0",
    "franc": "^4.1.0",
    "isomorphic-fetch": "^2.2.1",
    "pusher-js": "^4.4.0",
    "react-frame-component": "^4.1.0",
    "react-places-autocomplete": "^7.2.1",
    "styled-components": "^5.0.0-beta.6",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "terser": "^3.14.1",
    "terser-webpack-plugin": "^1.2.1",
    "@babel/core": "^7.1.0",
    "@babel/plugin-proposal-class-properties": "^7.2.3",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.2.0",
    "@hot-loader/react-dom": "^16.7.0",
    "babel-loader": "^8.0.4",
    "babel-plugin-add-module-exports": "^1.0.0",
    "clean-webpack-plugin": "^1.0.0",
    "css-loader": "^2.1.0",
    "file-loader": "^3.0.1",
    "html-webpack-plugin": "^3.2.0",
    "imagemin-gifsicle": "^6.0.1",
    "imagemin-jpegtran": "^6.0.0",
    "imagemin-optipng": "^6.0.0",
    "imagemin-svgo": "^7.0.0",
    "imagemin-webpack": "^4.0.1",
    "null-loader": "^0.1.1",
    "react-hot-loader": "^4.6.3",
    "sass": "^1.14.1",
    "sass-loader": "^7.1.0",
    "node-sass": "^4.11.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.28.3",
    "webpack-cli": "^3.1.2",
    "webpack-deep-scope-plugin": "^1.6.1",
    "webpack-dev-server": "^3.1.14",
    "react-day-picker": "^7.3.2",
    "evergreen-ui": "^4.18.1",
    "axios": "^0.19.0",
    "jsonwebtoken": "^8.5.1"
  }
}


`

**Comment by ericmarcos** [comment] 2020-06-04 07:12
Can't reproduce this issue with the latest version of Botonic (0.12.0).
Please share with us a repo where this behaviour can be reproduced, in the meantime I'll close this issue. Of course, feel free to reopen again if that's still happening to you.

**Closed by ericmarcos** 2020-06-04 07:12 UTC
Labels: bug
