### ISSUE TITLE
visual / screenshots? 

### ISSUE THREAD

**Issue by dcsan** [hubtype/botonic#1025] opened 2020-10-27 00:25 UTC
**Is your feature request related to a problem? Please describe.**
this looks interesting, but i'm not quite sure, i think the docs could be a lot clearer
I can't understand what the result of this framework is!

**Describe the solution you'd like**
since it's react i assume it's a client side framework - so it would be great to see how it looks 
also i think you have some widgets - I saw a calendar in the components dir
https://github.com/hubtype/botonic/tree/master/examples/hubtype_demo/src/webviews/components

so, it would be nice to have a library/listing of those components too!

finally is this meant to connect to a specific backend? I'm really unclear after looking at the docs.
where is the bot logic meant to be specified?

is that purely payloads => actions mapping?
https://botonic.io/docs/create-convapp

is there any other meta format for scripting?

thanks!

**Comment by ericmarcos** [comment] 2020-10-28 14:20
Hi @dcsan thanks for your feedback!
Your're right and we're currently working on providing better documentation and more examples =)

All the project is contained in the /src folder and we don't do an explicit differentiation between frontend/backend. When the project is built for local testing (`botonic serve`) we bundle everything together in a single js file to easily serve it in the browser. For production builds, we actually generate different bundles for Node (backend) and the browser (webchat frontend). When you do `botonic deploy` these bundles are uploaded to hubtype.com, where the Node parts are deployed on AWS Lambda and the frontend in a CDN (currently Netlify). In the future you'll be able to deploy a botonic project wherever you want.

I hope that clarifies how everything works under the hood. I'm closing this issue as it's not a bug or feat request. I encourage you to join our [Slack channel](slack.botonic.io) if you want to dive deeper or if you have suggestions on how to make a better documentation ;)

**Closed by ericmarcos** 2020-10-28 14:20 UTC
Labels: enhancement, good first issue, help wanted, up-for-grabs

**Comment by dcsan** [comment] 2020-10-28 15:50
So are there any screenshots anywhere?
